Python Web Workshop/accounts/urls.py
from django.urls import path, include
from .views import (
    profile_register,
    profile_login,
    profile_edit,
    profile_delete,
    profile_details,
)


urlpatterns = [
    path('register/', profile_register, name='profile register'),
    path('login/', profile_login, name='profile login'),
    path('profile/<int:pk>/', include([
        path('', profile_details, name='profile details'),
        path('edit/', profile_edit, name='profile edit'),
        path('delete/', profile_delete, name='profile delete'),
    ]))
]

Python Web Workshop/common/urls.py
from django.urls import path
from .views import home, like_functionality, share_functionality


urlpatterns = [
    path('', home, name='home'),
    path('like/<int:id>/', like_functionality, name='photo like'),
    path('share/<int:id>/', share_functionality, name='photo share')
]

Python Web Workshop/pets/urls.py
from django.urls import path, include
from .views import (
    pet_add,
    pet_delete,
    pet_details,
    pet_edit,
)


urlpatterns = [
    path('add/', pet_add, name='pet add'),
    path('<str:username>/pet/<slug:pet_slug>/', include([
        path('', pet_details, name='pet details'),
        path('edit/', pet_edit, name='pet edit'),
        path('delete/', pet_delete, name='pet delete'),
    ]))
]

Python Web Workshop/petstagram/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('accounts/', include('accounts.urls')),
    path('pets/', include('pets.urls')),
    path('photos/', include('photos.urls')),
]

Python Web Workshop/photos/urls.py
from django.urls import path, include
from .views import (
    photo_add,
    photo_details,
    photo_edit,
)


urlpatterns = [
    path('add/', photo_add, name='photo add'),
    path('<int:pk>/', include(
        [
            path('', photo_details, name='photo details'),
            path('edit/', photo_edit, name='photo edit'),
        ]
    )),
]

Python Web Workshop/accounts/models.py
from django.db import models

# Create your models here.

Python Web Workshop/common/models.py
from django.db import models
from photos.models import Photo


class Comment(models.Model):
    COMMENT_MAX_LENGTH = 300

    comment_text = models.TextField(
        max_length=COMMENT_MAX_LENGTH,
        null=False,
        blank=False,
    )
    date_of_publication = models.DateTimeField(
        auto_now_add=True,
    )
    to_photo = models.ForeignKey(
        Photo,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name='photo_comments',
    )

    class Meta:
        ordering = ['-date_of_publication']


class Like(models.Model):
    to_photo = models.ForeignKey(
        Photo,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name='photo_likes',
    )
    # TODO: When User is created
    # user = models.ForeignKey(User)

Python Web Workshop/pets/models.py
from django.db import models
from django.template.defaultfilters import slugify


class Pet(models.Model):
    name = models.CharField(
        max_length=30,
        null=False,
        blank=False,
    )
    personal_photo = models.URLField(
        null=False,
        blank=False,
    )
    date_of_birth = models.DateField(
        blank=True,
        null=True,
    )
    slug = models.SlugField(
        unique=True,
        editable=False,
    )


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(f'{self.name}-{self.id}')

        return super().save(*args, **kwargs)
    
    def __str__(self) -> str:
        return self.name

Python Web Workshop/photos/models.py
from django.db import models
from pets.models import Pet
from django.core.validators import MinLengthValidator
from django.core.exceptions import ValidationError
from petstagram.core.utils import mbytes_to_bytes


class Photo(models.Model):
    MAX_IMG_SIZE = 5.0
    DESCRIPTION_MAX_LENGTH = 300
    DESCRIPTION_MIN_LENGTH = 10
    LOCATION_MAX_LENGTH = 30

    def validate_max_img_size(self):
        if self.file.size > mbytes_to_bytes(Photo.MAX_IMG_SIZE ):
            raise ValidationError(f'Max file size is {Photo.MAX_IMG_SIZE}MB')
        
    photo = models.ImageField(
        null=False,
        blank=False,
        upload_to='photos/',
        validators=[validate_max_img_size]
    )
    description = models.TextField(
        null=True,
        blank=True,
        max_length=DESCRIPTION_MAX_LENGTH,
        validators=[MinLengthValidator(DESCRIPTION_MIN_LENGTH,)]
    )
    location = models.CharField(
        max_length=LOCATION_MAX_LENGTH,
        null=True,
        blank=True,
    )
    tagged_pets = models.ManyToManyField(
        Pet,
        blank=True,
        related_name='all_photos',
    )
    date_of_publication = models.DateField(
        auto_now=True,
    )

    @property
    def get_tagged_pets(self):
        if self.tagged_pets:
            return ', '.join(p.name for p in self.tagged_pets.all())
        return ''

Python Web Workshop/pets/forms.py
from django import forms
from .models import Pet


class PetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ['name', 'date_of_birth', 'personal_photo']
        labels = {
            'name': 'Pet Name',
            'personal_photo': 'Link to Image',
            'date_of_birth': 'Date of Birth',
        }
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Pet Name'}),
            'personal_photo': forms.TextInput(attrs={'placeholder': 'Link to Image'}),
            'date_of_birth': forms.DateInput(attrs={'placeholder': 'dd/mm/yyyy', 'type': 'date'}),
        }

Python Web Workshop/accounts/views.py
from django.shortcuts import render


def profile_register(request):
    return render(request, 'accounts/register-page.html')


def profile_login(request):
    return render(request, 'accounts/login-page.html')


def profile_details(request, pk):
    return render(request, 'accounts/profile-details-page.html')


def profile_edit(request, pk):
    return render(request, 'accounts/profile-edit-page.html')


def profile_delete(request, pk):
    return render(request, 'accounts/profile-delete-page.html')

Python Web Workshop/common/views.py
from django.shortcuts import render, redirect, resolve_url
from .models import Photo, Like
from pyperclip import copy


def to_url(request, id):
    return request.META['HTTP_REFERER'] + f'#photo-{id}'


def home(request):
    photos = Photo.objects.all()
    context = {'photos': photos}
    return render(request, 'common/home-page.html', context)


def like_functionality(request, id):
    Like.objects.create(to_photo_id=id)
    likes = Like.objects.filter(to_photo_id=id)
    if likes.count() > 1:
        [like.delete() for like in likes]
    return redirect(to_url(request, id))


def share_functionality(request, id):
    copy(request.META['HTTP_HOST'] + resolve_url('photo details', id))
    return redirect(to_url(request, id))

Python Web Workshop/pets/views.py
from django.shortcuts import render, redirect
from petstagram.core.utils import get_pet_by_name_and_slug
from .forms import PetForm


def pet_add(request):
    form = PetForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('profile details', pk=1) # TODO: user hardcode

    context = {'form': form}
    return render(request, 'pets/pet-add-page.html', context)


def pet_details(request, username, pet_slug):
    pet = get_pet_by_name_and_slug(pet_slug, username)
    total_photos_count = pet.all_photos.count()
    context = {'pet': pet, 'total_photos_count': total_photos_count}
    return render(request, 'pets/pet-details-page.html', context)

def pet_edit(request, username, pet_slug):
    return render(request, 'pets/pet-edit-page.html')

def pet_delete(request, username, pet_slug):
    return render(request, 'pets/pet-delete-page.html')

Python Web Workshop/photos/views.py
from django.shortcuts import render
from .models import Photo

def photo_add(request):
    return render(request, 'photos/photo-add-page.html')

def photo_details(request, pk):
    photo = Photo.objects.filter(pk=pk).first()
    tagged_pets = photo.tagged_pets.all()
    context = {'photo': photo, 'tagged_pets': tagged_pets}
    return render(request, 'photos/photo-details-page.html', context)

def photo_edit(request, pk):
    return render(request, 'photos/photo-edit-page.html')

Python Web Workshop/templates/accounts/login-page.html
{% extends 'common/base.html' %}

{% block content %}
<!-- Start Login Section-->
<div class="login-register-div">
    <div class="login-register-box">
        <h1>Petstagram</h1>

        <!-- Start Login Form-->
        <form action="#">
            <p>
                <label for="id_username">Username:</label>
                <input type="text" placeholder="Username">
            </p>
            <p>
                <label for="id_password">Password:</label>
                <input type="password" placeholder="Password">
            </p>

            <!-- Login Button-->
            <button type="submit">Log in</button>
        </form>
        <!-- End Login Form -->

    </div>
    <div class="second-option">

        <!-- Link to Register Page-->
        <p>Don't have account? <a href="{% url 'profile register' %}">Register</a></p>
    </div>
</div>
<!-- End Login Section-->
{% endblock %}

Python Web Workshop/templates/accounts/profile-delete-page.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
    <!-- Start Delete Profile Section -->
        <div class="delete-profile">
            <h1>
                Are you sure you want to delete your profile?
            </h1>
            <div class="sure-buttons">
                <!-- Yes (Delete Profile) Button -->
                <button>Yes</button>
                <!-- Go Back Button -->
                <a class="edit-btn" href="javascript:history.back()">Go Back</a>
            </div>
            <img src="{% static 'images/are_you_sure_cat.gif' %}" alt="are you sure cat git">
        </div>
    <!-- End Delete Profile Section -->
{% endblock %}

Python Web Workshop/templates/accounts/profile-details-page.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
    <!-- Start Profile Details Section -->
    <div class="profile">

        <!-- Start Profile Personal Data Section -->
        <div class="profile-data">
            <div class="profile_img">
                <div class="image">

                    <!-- Profile Image -->
                    <img src="{% static 'images/person.png' %}" alt="img8">
                </div>
            </div>
            <div class="personal">
                <div class="edit">
                    <!-- User Username -->
                    <p>d_kalaydzhiev</p>

                    <!-- IF the viewer is the owner of the profile -->
                    <!-- Link to Edit Profile Page -->
                    <!-- TODO: Add pk when profiles are available -->
                    <a href="{% url 'profile edit' 1 %}">
                        <img class="edit-img" src="{% static 'images/edit-pen-icon-6.jpg' %}" alt="edit button">
                    </a>

                    <!-- Link to Delete Profile Page -->
                    <!-- TODO: Add pk when profiles are available -->
                    <a href="{% url 'profile delete' 1 %}">
                        <img class="bin-img" src="{% static 'images/icon-remove-22.jpg' %}" alt="bin button">
                    </a>
                    <!-- End IF the viewer is the owner of the profile -->

                </div>
                <div class="data">

                    <!-- Total Number of Photos by the User -->
                    <span>4</span>
                    <p>photos</p>

                    <!-- Total Number of Pets owned by the User -->
                    <span>7</span>
                    <p>pets</p>

                    <!-- Total Number of Likes for the User -->
                    <span>436</span>
                    <p>likes</p>
                </div>
                <!-- User First and Last Name IF Added -->
                <h3 class="names">Diyan Kalaydziev</h3>

                <!-- User Email Address -->
                <p class="email">d.denov@gmail.com</p>

                <!-- User Gender IF Added -->
                <p class="gender">Male</p>
            </div>
        </div>
        <!-- End Profile Personal Data Section -->

        <!-- Start Pets Data Section -->
        <div class="pets">
            <div class="statuses">

                <!-- Start Pet Details Page -->
                <!-- Link to First Pet Details Page -->
                <!-- TODO: When profiles are available -->
                <a href="#">
                    <div class="head-pet">
                        <div class="status">
                            <div class="image">
                                <!-- Pet Image -->
                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgoIHq82qLYnvomfz5ZkW5CLQ8VNxCyI-hUw&usqp=CAU"
                                     alt="pet img">
                            </div>
                        </div>
                        <!-- Pet Name -->
                        <p>Sasho</p>
                    </div>
                </a>
                <!-- End Pet Details Page -->

            </div>
        </div>
        <!-- End Pets Data Section -->

        <!-- Start Last Uploaded Photos Section -->
        <div class="pet-photos">

            <!-- Link to Last Uploaded Pet Photo -->
            <a href="#">
                <!-- Pet Photo -->
                <img src="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631"
                     alt="pet img">
            </a>

            <!-- Link to Uploaded Pet Photo -->
            <a href="#">
                <!-- Pet Photo -->
                <img src="https://cf.ltkcdn.net/small-pets/images/orig/278587-1600x1066-goldfish-swimming-in-fish-tank.jpg"
                     alt="pet img">
            </a>

            <!-- Link to Uploaded Pet Photo -->
            <a href="#">
                <!-- Pet Photo -->
                <img src="https://thumbs.dreamstime.com/b/small-golden-retriever-puppy-6482030.jpg" alt="pet img">
            </a>

            <!-- Link to  Uploaded Pet Photo -->
            <a href="#">
                <!-- Pet Photo -->
                <img src="https://i.pinimg.com/originals/4e/55/83/4e5583748bc4000805df50e4ebcafffc.png" alt="pet img">
            </a>
        </div>
        <!-- End Last Uploaded Photos Section -->

    </div>
    <!-- End Profile Details Section -->
{% endblock %}

Python Web Workshop/templates/accounts/profile-edit-page.html
{% extends 'common/base.html' %}

{% block content %}
    <!-- Start Edit Profile Section -->
    <div class="edit-delete">
        <h2>Edit Profile</h2>
        <!-- Start Edit Profile From -->
        <form action="">
            <div class="label-input">
                <label for="first name">First name: </label>
                <input type="text" placeholder="First name" value="Diyan">
            </div>
            <br>
            <div class="label-input">
                <label for="last name">Last name: </label>
                <input type="text" placeholder="Last name" value="Kalayadzhiev">
            </div>
            <br>
            <div class="label-input">
                <label for="username">Username: </label>
                <input type="text" placeholder="Username" value="k_dido">
            </div>
            <br>
            <div class="label-input">
                <label for="email">Email: </label>
                <input type="email" placeholder="Email" value="d.denov@gmail.com">
            </div>
            <br>
            <div class="label-input">
                <label for="image">Image: </label>
                <input type="text" placeholder="Link to to profile picture"
                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631">
            </div>
            <br>

            <div class="label-input">
                <label for="image">Gender: </label>
                <div class="list-choice">
                    <div class="list-choice-title">Gender</div>
                    <div class="list-choice-objects">
                        <label>
                            <input type="radio" name="gender"/> <span>Male</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Female</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Do not show</span>
                        </label>
                    </div>
                </div>
            </div>

            <!-- Edit Profile Button -->
            <button class="edit-btn" type="submit">Edit</button>
        </form>
        <!-- End Edit Profile Form -->

    </div>
    <!-- End Edit Profile Section -->
{% endblock %}

Python Web Workshop/templates/accounts/register-page.html
{% extends 'common/base.html' %}

{% block content %}
    <!-- Start Register Section -->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Register Form -->
            <form action="">
                <input type="text" placeholder="Username">

                <input type="email" placeholder="Email">

                <input type="password" placeholder="Password">

                <input type="password" placeholder="Repeat Password">

                <!-- Register Button -->
                <button type="submit">Register</button>
            </form>
            <!-- End Register Form -->

        </div>
        <div class="second-option">

            <!-- Link to Login Page -->
            <p>Have an account? <a href="{% url 'profile login' %}">Log in</a></p>
        </div>
    </div>
    <!-- End Register Section -->
{% endblock %}

Python Web Workshop/templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->

<head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->

<body>
    {% include 'partial/header-nav.html' %}

    <!-- Start Main Content -->
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <!-- End Main Content -->

    <!-- Start Footer Section -->
    <div class="footer">
        <span class="footer-section">
            © 2022 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
        </span>
    </div>
    <!-- End Footer Section -->

</body>

</html>

Python Web Workshop/templates/common/home-page.html
{% extends 'common/base.html' %}

{% block content %}
<div class="container">
    <div class="col-9">

        <form class="searchbar" method="post">
            <input type="text" placeholder="Search by pet name...">
            <button>
                <img src="/static/images/search.png" height="18" alt="img2">
            </button>
        </form>

        {% for photo in photos %}
        {% include 'partial/pet-card.html' %}
        {% endfor %}

    </div>
</div>
{% endblock %}

Python Web Workshop/templates/partial/header-nav.html
    {% load static %}
    <!-- Starts Header Section with Navigation Bar -->
    <header>
        <nav class="navbar">
            <div class="container">
                <div class="logo">
                    <!-- Link to Home Page -->
                    <a href="{% url 'home' %}">
                        <img width="50px" src="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}" alt="img1">
                    </a>

                    <!-- Link to Home Page -->
                    <a class="home" href="{% url 'home' %}">
                        <i>Petstagram</i>
                    </a>
                </div>

                <div class="nav-links">
                    <ul class="nav-group">
                        <li class="nav-item">

                            <!-- Link to Add Pet Page -->
                            <a href="{% url 'pet add' %}">
                                <i>Add Pet</i>
                            </a>
                        </li>
                        <li class="nav-item">

                            <!-- Link to Add Photo Page -->
                            <a href="{% url 'photo add' %}">
                                <i>Add Photo</i>
                            </a>
                        </li>
                        <li class="nav-item">

                            <!-- Link to Login Page -->
                            <a href="{% url 'profile login' %}">
                                <i>Login</i>
                            </a>
                        </li>
                        <li class="nav-item">

                            <!-- Link to Register Page -->
                            <a href="{% url 'profile register' %}">
                                <i>Register</i>
                            </a>
                        </li>
                        <li class="nav-item">

                            <!-- TODO: add profile pk when available -->
                            <!-- Link to Profile Page -->
                            <a href="{% url 'profile details' 1 %}">
                                <i>Profile</i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <!-- End Header Section with Navigation Bar -->

Python Web Workshop/templates/partial/like-share-section.html
<div class="actionBtns">
    <div class="left">

        <span class="heart">
            <a href="{% url 'photo like' photo.id %}">
                {% if photo.photo_likes.count > 0 %}
                <svg style="color: red" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                    fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                    <!-- Coordinate path -->
                    <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735
                                  8 15-7.534 4.736 3.562-3.248 8 1.314z" fill="red">

                    </path>
                </svg>
                {% else %}
                <svg aria-label="Like" color="#262626" fill="#262626" height="24" role="img"
                    viewBox="0 0 48 48" width="24">
                    <!-- Coordinate path -->
                    <path d="M34.6 6.1c5.7 0 10.4 5.2 10.4
                                    11.5 0 6.8-5.9 11-11.5 16S25 41.3 24
                                    41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3
                                    11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3
                                    1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9
                                    1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9
                                    1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1
                                    0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3
                                    1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3
                                    1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2
                                    7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6
                                    48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                    </path>
                </svg>
                {% endif %}
            </a>
        </span>
        
        <a href="{% url 'photo share' photo.id %}">
            <svg aria-label="Share Post" class="_8-yf5 " color="#262626" fill="#262626" height="24"
                role="img" viewBox="0 0 48 48" width="24">
                <path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3
                        3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6
                        1 1.2 1.1h.2c.5 0 1-.3
                        1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2
                        6.1h35.5L18 18.7 5.2 6.1zm18.7
                        33.6l-4.4-18.4L42.4 8.6 23.9 39.7z">
                </path>
            </svg>
        </a>
        
    </div>

</div>

<p class="likes">{{photo.photo_likes.count}} likes</p>

Python Web Workshop/templates/partial/pet-card.html
<div class="card">
    <div class="top">
        <!-- TODO: User Details and image location -->
        <div class="userDetails">
            <a href="profile details">
                <div class="profilepic">
                    <div class="profile_img">
                        <div class="image">
                            <img src="/static/images/person.png" alt="img8">
                        </div>
                    </div>
                </div>
            </a>
            <h3>
                <a href="profile details">
                    <!-- if user has first name and last name -->
                    Diyan Kalaydzhiev
                    <!-- else -->
                    <!-- user username -->
                </a>
                <br>
                {% if photo.location %}
                <span>{{photo.location}}</span>
                {% endif %}
            </h3>
        </div>
    </div>

    <!-- Post image -->
    <div class="imgBx" id="photo-{{photo.id}}">
        <img src="/static/images/axolotl.jpeg" alt="post" class="cover">
    </div>
    <!-- -->
    {% include 'partial/photo-bottom.html' %}
</div>

Python Web Workshop/templates/partial/photo-bottom.html
<div class="bottom">
    {% include 'partial/like-share-section.html' %}

    {% for pet in photo.tagged_pets.all %}
    <!-- TODO: fix it when user authenticated -->
    <a href="{% url 'pet details' username='sasho' pet_slug=pet.slug %}">
        <p class="message">
            <b>{{ pet.name }}</b>
        </p>
    </a>
    {% endfor %}

    <a href="{% url 'photo details' photo.id %}">
        <h4 class="details">See details</h4>
    </a>

    <h5 class="postTime">{{ photo.date_of_publication }}</h5>

    <!-- TODO: Start Add Comments Section -->
    <div class="addComments">
        <div class="reaction">
            <h3>
                <i class="far fa-smile"></i>
            </h3>
        </div>
        <!-- Start Add Comments Form -->
        <form method="post" action="#">
            <label for="id_body">Body:</label>
            <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                required="" id="id_body"></textarea>
            <button type="submit">Post</button>
        </form>
        <!-- End Add Comments Form -->

    </div>
    <!-- End Add Comments Section -->

</div>

Python Web Workshop/templates/pets/pet-add-page.html
{% extends 'common/base.html' %}

{% block content %}
    <!-- Start Add Pet Section-->
    <div class="edit-delete edit-photo">
        <h2>Add pet</h2>

        <!-- Start Add Pet Form -->
        <form action="{% url 'pet add' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <!-- Add Pet Button -->
            <button class="add-btn" type="submit">Add Pet</button>
        </form>
        <!-- End Add Pet Form -->

    </div>
    <!-- End Add Pet Section -->
{% endblock %}

Python Web Workshop/templates/pets/pet-delete-page.html
{% extends 'common/base.html' %}

{% block content %}
    <!-- Starts Delete Pet Section -->
    <div class="edit-delete edit-photo">
        <h2>Delete pet</h2>
        <!-- Starts Delete Pet Form -->
        <form action="#">
            <p>
                <label for="pet-name">Pet name: </label>
                <input type="text" placeholder="Name" value="Sasho" disabled>
            </p>
            <p>
                <label for="pet-date">Date of birth: </label>
                <input type="date" disabled>
            </p>
            <p>
                <label for="pet-image">Link to image: </label>
                <input type="text" placeholder="Link to image"
                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631"
                       alt="pet image" disabled>
            </p>
            <!-- Delete Pet Button -->
            <button class="delete-btn" type="submit">Delete</button>
            <!-- Go Back Button -->
            <a class="btn btn-primary" href="javascript:history.back()">
                <button class="edit-btn" type="button">Go back</button>
            </a>
        </form>
        <!-- End Delete Pet Form -->
    </div>
    <!-- End Delete Pet Section -->
{% endblock %}

Python Web Workshop/templates/photos/photo-add-page.html
{% extends 'common/base.html' %}

{% block content %}
    <!-- Start Add Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Add photo</h2>
        <!-- Start Add Photo Form -->
        <form action="" enctype="multipart/form-data">
            <p>
                <label for="id_photo_file">Photo file:</label>
                <input type="file">
            </p>

            <p>
                <label for="id_description">Description:</label>
                <input type="text">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>
            <!-- Add Photo Button -->
            <button class="add-btn" type="submit">Add Photo</button>
        </form>
        <!-- End Add Photo Form -->
    </div>
    <!-- End Add Photo Section -->
{% endblock %}

Python Web Workshop/templates/photos/photo-edit-page.html
{% extends 'common/base.html' %}

{% block content %}
    <!-- Starts Edit Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit photo</h2>

        <!-- Starts Edit Photo Form -->
        <form action="">
            <p>
                <label for="id_photo_file">Photo file:</label>
                <input type="file">
            </p>

            <p>
                <label for="id_description">Description:</label>
                <input type="text" value="Sasho is an Axolotl">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location"
                       value="Bansko, Bulgaria">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option selected>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>

            <!-- Edit Photo Button -->
            <button class="edit-btn" type="submit">Edit Photo</button>
        </form>
        <!-- End Edit Photo Form -->

    </div>
    <!-- End Edit Photo Section -->
{% endblock %}